package com.xafdy.model;

public class College {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column college.id
	 * @mbg.generated  Wed Mar 28 16:28:27 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column college.name
	 * @mbg.generated  Wed Mar 28 16:28:27 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column college.intro
	 * @mbg.generated  Wed Mar 28 16:28:27 CST 2018
	 */
	private String intro;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column college.id
	 * @return  the value of college.id
	 * @mbg.generated  Wed Mar 28 16:28:27 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column college.id
	 * @param id  the value for college.id
	 * @mbg.generated  Wed Mar 28 16:28:27 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column college.name
	 * @return  the value of college.name
	 * @mbg.generated  Wed Mar 28 16:28:27 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column college.name
	 * @param name  the value for college.name
	 * @mbg.generated  Wed Mar 28 16:28:27 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column college.intro
	 * @return  the value of college.intro
	 * @mbg.generated  Wed Mar 28 16:28:27 CST 2018
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column college.intro
	 * @param intro  the value for college.intro
	 * @mbg.generated  Wed Mar 28 16:28:27 CST 2018
	 */
	public void setIntro(String intro) {
		this.intro = intro;
	}
}