package com.xafdy.model;

import java.util.Date;

public class CourseFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_file.id
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_file.path
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_file.course_id
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_file.record_time
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_file.teacher_id
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    private Integer teacherId;
    
    private String courseName;
    

    public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_file.id
     *
     * @return the value of course_file.id
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_file.id
     *
     * @param id the value for course_file.id
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_file.path
     *
     * @return the value of course_file.path
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_file.path
     *
     * @param path the value for course_file.path
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_file.course_id
     *
     * @return the value of course_file.course_id
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_file.course_id
     *
     * @param courseId the value for course_file.course_id
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_file.record_time
     *
     * @return the value of course_file.record_time
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_file.record_time
     *
     * @param recordTime the value for course_file.record_time
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_file.teacher_id
     *
     * @return the value of course_file.teacher_id
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_file.teacher_id
     *
     * @param teacherId the value for course_file.teacher_id
     *
     * @mbg.generated Thu Mar 29 17:40:13 CST 2018
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}