package com.xafdy.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.num
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.college_id
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    private Integer collegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.telphone
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id_card_no
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.account
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    private String password;
    
    private String collegeName;
    
    private String genderName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public Integer getId() {
        return id;
    }
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.num
     *
     * @return the value of student.num
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.num
     *
     * @param num the value for student.num
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.college_id
     *
     * @return the value of student.college_id
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.college_id
     *
     * @param collegeId the value for student.college_id
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.telphone
     *
     * @return the value of student.telphone
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.telphone
     *
     * @param telphone the value for student.telphone
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id_card_no
     *
     * @return the value of student.id_card_no
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id_card_no
     *
     * @param idCardNo the value for student.id_card_no
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.account
     *
     * @return the value of student.account
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.account
     *
     * @param account the value for student.account
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbg.generated Wed Mar 28 21:14:50 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }



	public String getCollegeName() {
		return collegeName;
	}



	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}



	public String getGenderName() {
		return genderName;
	}



	public void setGenderName(String genderName) {
		this.genderName = genderName;
	}
    
}